{
  "login": "supreetsingh247",
  "id": 7427552,
  "avatar_url": "https://avatars1.githubusercontent.com/u/7427552?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/supreetsingh247",
  "html_url": "https://github.com/supreetsingh247",
  "followers_url": "https://api.github.com/users/supreetsingh247/followers",
  "following_url": "https://api.github.com/users/supreetsingh247/following{/other_user}",
  "gists_url": "https://api.github.com/users/supreetsingh247/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/supreetsingh247/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/supreetsingh247/subscriptions",
  "organizations_url": "https://api.github.com/users/supreetsingh247/orgs",
  "repos_url": "https://api.github.com/users/supreetsingh247/repos",
  "events_url": "https://api.github.com/users/supreetsingh247/events{/privacy}",
  "received_events_url": "https://api.github.com/users/supreetsingh247/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Supreet Singh",
  "company": "Target Corporation",
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "Front end developer since 1.5 years",
  "public_repos": 11,
  "public_gists": 0,
  "followers": 2,
  "following": 2,
  "created_at": "2014-04-28T09:44:57Z",
  "updated_at": "2018-05-18T16:23:36Z"
